tried to improve the main layout and styling of the home-page, still …
grossjungig/frontend pull request #23
Opened 2021-03-30 14:51 UTC by luc-sauvage

…things to be clarified

hey Morteza here's a first cleanup, following the designs in figma... there are a few things which we need to discuss

2021-03-31 14:31 UTC, luc-sauvage commented on src/pages/home/home.css
> +.button-not-button {
a div which looks like a button but it's not... but yes you are right, i will change it!

2021-03-31 14:31 UTC, luc-sauvage commented on src/pages/home/Home.js
> +          <H2 titleColor="white" style={{ textAlign: "center", marginBottom: "1.5rem" }}>{homeLocales.how[lang]}</H2>
i will!

2021-03-31 14:48 UTC, luc-sauvage commented on src/pages/home/Home.js
> +          <H2 titleColor="white" style={{ textAlign: "center", marginBottom: "1.5rem" }}>{homeLocales.how[lang]}</H2>
done

2021-03-31 14:48 UTC, luc-sauvage commented on src/pages/home/home.css
> +.button-not-button {
done! I used `.category-title`

2021-03-31 14:48 UTC, luc-sauvage commented on src/pages/home/home.css
> +  background-position: 0 120%;
i set `background-position: bottom` here

2021-03-31 14:48 UTC, luc-sauvage commented on src/pages/home/Home.js
> +        {/* <CommunityPanel id="community">
done!

2021-04-09 16:22 UTC, nancologist requested changes

2021-04-09 16:22 UTC, nancologist commented on src/components/styled.js
> +  margin: 1rem;
Please use pixel unit (px).

2021-04-09 16:22 UTC, nancologist commented on src/components/styled.js
> +
please use pixel units

2021-04-09 16:22 UTC, nancologist commented on src/components/styled.js
> +  padding: 1rem 1.5rem;
pixel units please

2021-04-09 16:22 UTC, nancologist commented on src/components/styled.js
> +  padding: 2rem;
please use px

2021-04-09 16:22 UTC, nancologist commented on src/pages/home/styled.js
> +  background-image: url("./image/playstation.jpg");
Please add your picture to the ``assets/`` and then import the picture in this js file and then use ``${}`` as argument for url()

2021-04-09 16:22 UTC, nancologist commented on src/pages/home/home.css
> +  background-image: url("../../assets/images/backgrounds/hero-home-background-picture.jpg");
please import the picture and then use the name of variable here in a ${} string interpolation

2021-04-10 17:56 UTC, merged